# Generated by Django 5.2.17 on 2026-09-30 06:22

from django.db import migrations, models
from django.db.models import Count, OuterRef, Subquery


def backfill_timestamps_and_check_duplicates(apps, schema_editor):
    Answer = apps.get_model("feedback", "Answer")
    Response = apps.get_model("feedback", "Response")

    # Existing answers have no timestamp of their own; the closest truthful value
    # is when their response was submitted.
    submitted_at = Subquery(
        Response.objects.filter(pk=OuterRef("response_id")).values("submitted_at")[:1]
    )
    Answer.objects.filter(created_at__isnull=True).update(
        created_at=submitted_at, updated_at=submitted_at
    )

    # A unique (response, question) constraint follows; fail with a readable
    # message instead of a raw IntegrityError if the data would violate it.
    duplicates = (
        Answer.objects.values("response_id", "question_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    if duplicates.exists():
        sample = list(duplicates[:10])
        raise RuntimeError(
            f"Found {duplicates.count()} (response, question) pairs with more than "
            f"one answer, e.g. {sample}. Remove the duplicates before migrating."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(
            backfill_timestamps_and_check_duplicates,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
