# Generated by Django 5.2.17 on 2026-09-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_answer_timestamps_required'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['submitted_at', 'id'], name='response_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['status', 'submitted_at', 'id'], name='response_status_submitted_idx'),
        ),
    ]
