# Generated by Django 5.2.17 on 2026-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_response_listing_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='rating_labels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
