# Generated by Django 5.2.17 on 2026-09-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_multiselect_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('rating', 'Rating'), ('multiselect', 'Multi-select'), ('comment', 'Comment')], default='rating', max_length=20),
        ),
    ]
