# Generated by Django 5.2.17 on 2026-09-30 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_comment_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='edit_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='AnswerRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('answered_at', models.DateTimeField()),
                ('replaced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='feedback.answer')),
            ],
            options={
                'ordering': ['answered_at', 'id'],
            },
        ),
    ]
