# Generated by Django 5.2.17 on 2026-09-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_answer_revisions_and_edit_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
