# Generated by Django 5.2.17 on 2026-09-30 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_question_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='condition_operator',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='condition_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='feedback.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='condition_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
